### ISSUE TITLE
Does not work with Ruby 3.3

### ISSUE THREAD

**Issue by JacobEvelyn** [zverok/dokaz#3]
Unfortunately despite #1, this now seems to no longer work with Ruby 3.3. I tried digging in to understand what to fix but don't follow enough to know. The error I'm getting is:

```
gems/dokaz-0.0.5/lib/dokaz/parser.rb:77:in `parse!': undefined method `set_input' for an instance of IRB::RubyLex (NoMethodError)

        lex.set_input(SpecIO.new(code))
```

**Comment by zverok** [comment]
@JacobEvelyn I’ll try to look into it once, but I can’t promise anything. I don’t have much time on my hands (serving in the Ukrainian Armed Forces), and I currently don’t use `dokaz` myself.

I still love the idea of the gem and want it to be useful, but it was created many years ago as a weekend project, a quick hack around IRB’s internal APIs — and probably, in order to live and prosper, it should be updated to use more robust APIs. It is hard to estimate how long the investigation might be.

I would be happy to accept a PR, though.

**Comment by JacobEvelyn** [comment]
Hey @zverok, thanks for the reply. I had seen the 🇺🇦 flag in your bio and wasn't sure if you'd even be able to respond at all, so I appreciate the time. I probably won't have time to investigate this, but fixing it is not important for our team so please don't feel pressure from me/us to spend time here.

Stay safe. My thoughts are with you. ❤️
